brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 容器内网：客户端（app）通过服务名 broker 访问
brokerIP1 = broker
namesrvAddr = namesrv:9876
autoCreateTopicEnable = true
